version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: virtus-nginx
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Monta i certificati SSL dalla directory del server
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - frontend-dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    command: ["nginx", "-g", "daemon off;"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtus-angular
    volumes:
      - frontend-dist:/app/dist
    restart: unless-stopped

volumes:
  frontend-dist: