version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: virtus-nginx
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - frontend-dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtus-angular
    volumes:
      - frontend-dist:/app/dist

  certbot:
    image: certbot/certbot
    container_name: virtus-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done'"
  
volumes:
  frontend-dist:
